### PR TITLE
lint

### PR DESCRIPTION
**Pull request by PascalBourdier**

### CODE REVIEW

**Comment by jlruizmlg** [comment]
hi @PascalBourdier thanks! let me check that because is strange, we usually pass the lint to our code, in fact, if you take a look from the score in forge.puppet.com is a 5 over 5

https://forge.puppet.com/wazuh/ossec/scores

**Comment by PascalBourdier** [comment]
Yes but I lint with the last version of puppet-lint

**Comment by jlruizmlg** [comment]
Hi @PascalBourdier, which is your lint version? i'm running with the 2.2.1 and still no having errors like your pull request, sorry for the question i like to be in the same page than you before merge, is a big pull request.

**Comment by PascalBourdier** [comment]
2.2.1 too but I use ruby 2.1.10

**Comment by jlruizmlg** [comment]
We will pass puppet lint after finish all pull request.

**Pull request closed without merging**
