### PR TITLE
add parametrized owner/group for windows Administrator account

### PR DESCRIPTION
**Pull request by lmayorga1980**

### CODE REVIEW

**Comment by lmayorga1980** [comment]
@jlruizmlg I just added support for ubuntu docker image.

**Comment by lmayorga1980** [comment]
can someone check this merge request?

**Comment by lmayorga1980** [comment]
??

**Comment by jlruizmlg** [comment]
Hi @lmayorga1980 sorry for the late response, I could understand the option to change the owner and group in windows, but could you tell me an use case for the docker image?, not sure in what case we want to use this feature.

**Comment by lmayorga1980** [comment]
@jlruizmlg the docker image is to quickly test the project. Is not part of the code deployment and is just part of the beaker-rspec testing framework.

**Comment by jlruizmlg** [comment]
Hi @lmayorga1980 you are right!, sorry for the idiot question.

**Pull request merged**
