### PR TITLE
Add Amazon Linux support

### PR DESCRIPTION
**Pull request by seefood**
Support Amazon Linux - it's RH-like, but not exactly, needs a special case for the yum repo.

### CODE REVIEW

**Comment by jlruizmlg** [comment]
Hi @seefood sorry for the delay thank! i will try and let you know!

**Comment by jlruizmlg** [comment]
Hi @seefood im looking this configuration after try in an amazon instance i have this result

```
[root@ip-10-0-0-231 ec2-user]# facter name
[root@ip-10-0-0-231 ec2-user]# facter operatingsystem
Amazon
[root@ip-10-0-0-231 ec2-user]#
```
Are you sure are you sure is ```facts['os']['name']```?
I can't try right now in Amazon this configuration.

**Comment by seefood** [comment]
It's the latest puppet 4 and facter 3.X , you may be using puppet 3 and facter 2? in which case the parameters (and facts[] array) may look different. 

here's the relevant part of the facter output on my setup:
```
[root@ob2-hipaa1 ~]# facter --version ; facter os
3.4.0 (commit c86b3086f45c9de980fd23176c15e37fddf20cd4)
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "Amazon",
  release => {
    full => "4.4.15-25.57.amzn1.x86_64",
    major => "4",
    minor => "4"
  },
  selinux => {
    enabled => false
  }
}
```
Compare with:
```
[root@mon-app2 ~]# facter --version ; facter os
3.3.0 (commit fc9282a2d426f7c8a742fd5b23c4cb06852eee20)
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.2.1511",
    major => "7",
    minor => "2"
  },
  selinux => {
    enabled => false
  }
}
```

**Comment by seefood** [comment]
Ahh, looks like the old syntax is still supported too I guess.
```
[root@ob2-hipaa1 ~]# facter operatingsystem
Amazon
```

**Comment by jlruizmlg** [comment]
hi @seefood , so what do you think? we move to operatingsystem instead name to support the old agents?

**Comment by seefood** [comment]
Sure.

**Comment by seefood** [comment]
Fixed, but I see you already merged, so opened a new PR.

**Pull request merged**
