### PR TITLE
	Add option to set syslog output port

### PR DESCRIPTION
**Pull request by markasammut**

### CODE REVIEW

**Comment by jlruizmlg** [comment]
hi @markasammut thanks for the pull request, i need to review, only one question the pull request 7ea51cc don't should be here right?

**Comment by markasammut** [comment]
Hmm I didn't notice it was included in my pull-request. Well, for our case we have to remove that dependency, as we use a custom mysql module which allows for replication.

**Comment by jlruizmlg** [comment]
@markasammut may I cancel the pull request and do the changes manually? thinks like delete the 7ea51cc we don't want to delete, also after accept the last pull request now we have some conflicts.

**Comment by jlruizmlg** [comment]
Hi @markasammut im going to close this pull request, please clean a little the pull request from your own modifications and send us again!

We appreciate your contribution!

**Pull request closed without merging**
