### PR TITLE
add support to download file without chocolatey installation

### PR DESCRIPTION
**Pull request by lmayorga1980**
* remove windows binary from `files/`
* add two new parameters `agent_chocolatey_enabled` and `agent_download_url`(only for non-chocolatey installations).
* update serverspec test for ossec-agent 2.8

### CODE REVIEW

**Comment by lmayorga1980** [comment]
@jlruizmlg added support for non-chocolatey installations and also provide a way to switch the behavior or the beaker test by using `OSSEC_CHOCOLATEY_ENABLED=true`

**Comment by jlruizmlg** [comment]
Thaks for your contribution @lmayorga1980 looks amazing!

**Comment by lmayorga1980** [comment]
@jlruizmlg let me know whenever you merge against master.

**Comment by jlruizmlg** [comment]
Hi @lmayorga1980 I just update a few things on your last pull request https://github.com/wazuh/ossec-puppet/commit/be47dd826bc8364616cfe000ace6b2db1b780b43

- Changed the ossec-HIDS URL because doesn't exist.
- Setup to "false" the chocolatey installation, right now the manager is 2.8.3 and is not recommended to install agents in a higher version, after release the packages 2.9 we can setup to True, that make sense for you?

**Comment by lmayorga1980** [comment]
@jlruizmlg Yeah it makes sense. I forgot about the current version.

**Pull request merged**
