### PR TITLE
Feature/wazuh rulesets

### PR DESCRIPTION
**Pull request by seefood**
Added manifests to potentially download and install the the Wazuh rules. and even install as a cronjob. the cron option not well parameterized, It's more of a Quick&Dirty example code.

### CODE REVIEW

**Comment by seefood** [comment]
any takers?

**Comment by jlruizmlg** [comment]
Hi @seefood sorry for the delay thank! i will try and let you know!

**Comment by jlruizmlg** [comment]
Hi @seefood thanks for your contribution, i see a couple problems with this pull request, 

- When the manifest run ```ossec_ruleset.py``` this python modify ```ossec.conf``` with two new lines adding two decoders directores so we need to do modifications in the  template ```10_ossec.conf.erb``` , adding the following lines:
   - ```<decoder_dir>etc/ossec_decoders</decoder_dir>```
   - ```<decoder_dir>etc/wazuh_decoders</decoder_dir>```
- In the wget:fetch class, the file ```ossec_ruleset.py``` is downloaded every time than you run the manifest because don't have any unless, so download and run the script each time. Usually in a normal environment the manifest run every 30min by default https://docs.puppet.com/puppet/latest/reference/man/agent.html#USAGE-NOTES so could be nice modify this option to only run once after download the file if the file doesn't have modifications.
- I see the crontab manifest but its not called by other manifest right?

Let me know if this three things make sense for you, thanks!

**Comment by jlruizmlg** [comment]
Hi @seefood after checking with  the Wazuh developer team, I am told the next Ossec ruleset version will only be compatible with OSSEC Wazuh.  Sorry but I cannot merge this pull request with this ossec version; ossec ruleset will be available in the Wazuh module.

**Comment by seefood** [comment]
Well, the wget downloads it on every run to a cache dir, but only runs it if it has updated. suboptimal, but there's no other way to make sure it's up to date.
As for the rules working only wit the wuzah fork - I thought that's the version this module is installing anyway...
As for the extra lines in the config, I just added them in invocation:
```
    class { 'ossec::server':
      mailserver_ip             => 'localhost',
      ossec_emailto             => ["devops+${::hostname}@example.com"],
      ossec_emailfrom           => "ossec@${::fqdn}",
      use_mysql                 => false,
      ossec_email_alert_level   => 6,
      ossec_install_wazuh_rules => true,
      ossec_extra_rules_config  => [
        '<decoder_dir>etc/ossec_decoders</decoder_dir>',
        '<decoder_dir>etc/wazuh_decoders</decoder_dir>',
        '<decoder>etc/local_decoder.xml</decoder>',
        '<include>auditd_rules.xml</include>',
        '<include>usb_rules.xml</include>',
        '<include>opensmtpd_rules.xml</include>',
        '<include>amazon_rules.xml</include>',
        '<include>amazon-ec2_rules.xml</include>',
        '<include>amazon-iam_rules.xml</include>',
        '<include>firewalld_rules.xml</include>',
        '<include>ossec_ruleset_rules.xml</include>',
        '<include>puppet_rules.xml</include>',
        '<include>unbound_rules.xml</include>',
        '<include>web_appsec_rules.xml</include>',
        '<include>systemd_rules.xml</include>'
      ],
      manage_client_keys        => false
    }

```
Finally, The cron manifest is added as an example. to force it would be a bad idea, since a proper opsec approach would be to check updates from a third party before installing them blindly.

**Comment by jlruizmlg** [comment]
Hi @seefood to me the notifies run always, even if the file its the same than the previously ...

**Pull request closed without merging**
